PATH := node_modules/.bin:$(PATH)

STYLUS_FILES := $(shell find ./public/styl -name \*.styl -print)

#All files which aren't generated by running make
HTML_SOURCE_FILES := $(shell find . -not -name "*.css" -not -name "*.html" -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./public/*" -type f -print)


# Tasks
.PHONY: update-contributors dist force

all: build

# Rebuild jade/css/html etc, does not by default grab new readmes/contributors
build: index.html public/css/main.css

# This updates the contributors lists and all the readmes
update-live-data: update-contributors update-readmes



index.html: $(HTML_SOURCE_FILES)
	node build.js

public/css/main.min.css: public/css/main.css
	cssmin public/css/main.css > public/css/main.min.css

public/css/main.css: public/styl/main.styl $(STYLUS_FILES)
	stylus -I public/styl < $< > $@

update-contributors:
	node lib/calculate-contributions.js
	node lib/get-core-contributors.js

update-readmes: force
	node build.js
